[build]
  publish = "dist/tripadvisor"
  command = "ng build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api"
  to = "https://proxy-server-2307.up.railway.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}